# Generated by Django 6.0.5 on 2026-05-20 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_personaje', models.CharField(max_length=150, verbose_name='Nombre del personaje')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='personajes/', verbose_name='Imagen')),
                ('juego_donde_sale', models.CharField(max_length=200, verbose_name='Juego donde sale')),
                ('rol', models.CharField(choices=[('cantante', 'Cantante'), ('guitarrista', 'Guitarrista'), ('baterista', 'Baterista'), ('espectaculo', 'Espectáculo'), ('animatronic', 'Animatrónico'), ('seguridad', 'Seguridad'), ('antagonista', 'Antagonista'), ('ayudante', 'Ayudante'), ('otro', 'Otro')], default='animatronic', max_length=50, verbose_name='Rol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('variantes', models.ManyToManyField(blank=True, related_name='variante_de', to='api.personaje', verbose_name='Variantes')),
            ],
            options={
                'verbose_name': 'Personaje',
                'verbose_name_plural': 'Personajes',
                'ordering': ['nombre_personaje'],
            },
        ),
    ]
